spring:
  application:
    name: comment-service

  datasource:
    url: jdbc:postgresql://
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 2

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: update
    open-in-view: false

server:
  port: 8083
  servlet:
    context-path: /api/v1

eureka:
  instance:
    instance-id: ${spring.application.name}
    non-secure-port: ${server.port}
    hostname: localhost
  #    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    fetch-registry: true
    register-with-eureka: true

application:
  config:
    client:
      uri:
        user-service: http://user-service/api/v1/users
        post-service: http://post-service/api/v1/posts

